todoapp/coreapp/urls.py
from django.urls import path

from . import views


app_name = "coreapp"

urlpatterns = [
    path("", views.MainPageView.as_view(), name='main-page'),
    
    path("edittask/<int:id>", views.EditTaskView.as_view(), name='edit-task'),
    
    path("imptasks/", views.ImportantTasksView, name='imp-tasks'),
    
    path("completedtasks/", views.CompletedTasksView, name='completed-tasks'),
    
    path('deletetask/<int:id>', views.DeleteTaskView, name='delete-task'),
    
    path('donetask/<int:id>', views.DoneTaskView, name='done-task'),
    
    path('incompletetask/<int:id>', views.IncompleteTaskView, name='incomplete-task'),
]

todoapp/todoapp/urls.py
from django.contrib import admin
from django.urls import path, include, re_path

from django.views.static import serve
from django.conf import settings
from django.conf.urls import handler404, handler500
from django.conf.urls.static import static

from django.contrib.staticfiles.storage import staticfiles_storage
from django.views.generic.base import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include('coreapp.urls')),
    path('favicon.ico', RedirectView.as_view(url=staticfiles_storage.url('favicon/favicon.ico'))),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
else:
    urlpatterns += ( re_path(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}), )

handler404 = 'coreapp.views.custom_404'

todoapp/coreapp/models.py
from django.db import models

# Create your models here.

class Task(models.Model):
    title = models.TextField(max_length=500)
    is_important = models.BooleanField(default=False, blank=True)
    is_complete = models.BooleanField(default=False)
    
    def __str__(self):
        return f"{self.title}"

todoapp/coreapp/forms.py
from django import forms

from .models import Task


class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ["title", "is_important"]
        labels = {
            "title": "Todo",
        }
        widgets = {
            "title": forms.TextInput(attrs={'class': 'myfieldclass'})
        }

 
    def clean(self):
        super(TaskForm, self).clean()
        title = self.cleaned_data.get('title')
        if len(title) < 3:
            self._errors['title'] = self.error_class([
                        'Please enter todo item.'])    
        self.cleaned_data['title'] = title.lower()
        return self.cleaned_data
    

todoapp/coreapp/views.py
from typing import Any
from django.db.models.query import QuerySet
from django.shortcuts import render, redirect
from django.shortcuts import get_object_or_404

from django.views import View

from .models import Task
from .forms import TaskForm

# Create your views here.
class MainPageView(View):
    """ to list all tasks and create a new task"""
    
    def get(self, request):
        """ to list all not completed tasks"""
        tasks_list = Task.objects.filter(is_complete=False)
        context = {
            "form": TaskForm(),
            "tasks_list": tasks_list,
            "error_mssg": "",
        }
        return render(request, "coreapp/mainpage.html", context)
    
    def post(self, request):
        """ to create a new task"""
        submitted_taskform = TaskForm(request.POST or None)  
        if submitted_taskform.is_valid():
            new_todo = submitted_taskform.cleaned_data['title']
            if Task.objects.filter(title=new_todo.lower(),is_complete=False).exists():
                error_mssg = "You already have added this to your list"
                form = submitted_taskform
            else:
                error_mssg = ""
                form = TaskForm()
                submitted_taskform.save()
            context = {
                "form": form,
                "tasks_list": Task.objects.filter(is_complete=False),
                "error_mssg": error_mssg,
            }
            return render(request, "coreapp/mainpage.html", context)
        else:
            return render(request, "coreapp/mainpage.html", {"form": submitted_taskform})
       
      
    
class EditTaskView(View):
    """ to edit a task"""
    
    def get(self, request, id):
        """ to display task that is to be edited"""
        try:
            task = Task.objects.get(pk=id)
        except :
            tasks_list = Task.objects.filter(is_complete=False)
            task_form = TaskForm()
            context = {
                "form": task_form,
                "tasks_list": tasks_list,
                "id": id,
                "error_mssg": "Task Doesnot exists"
            }
            return render(request, "coreapp/edittask.html", context)
        else:
            tasks_list = Task.objects.filter(is_complete=False).exclude(id=id)
            task_form = TaskForm({"title": task.title, "is_important": task.is_important})
            context = {
                "form": task_form,
                "tasks_list": tasks_list,
                "id": id,
                "error_mssg": ""
            }
            return render(request, "coreapp/edittask.html", context)

    def post(self, request, id):
        """ updates the task title field and is_important field """
        edited_taskform = TaskForm(request.POST)
        if edited_taskform.is_valid():
            
            new_task_title = edited_taskform.cleaned_data.get('title')
            new_task_imp = edited_taskform.cleaned_data.get('is_important')  
            tasks_list = Task.objects.filter(is_complete=False)
                
            if Task.objects.filter(title=new_task_title.lower(),is_complete=False).exists():
                """ check if the updated task is already present in the db"""
                error_mssg = "You already have added this to your list"
                context = {
                    "form": edited_taskform,
                    "tasks_list": tasks_list,
                    "error_mssg": error_mssg,
                    "id": id
                }
                return render(request,"coreapp/edittask.html", context)
           
            task = Task.objects.get(id=id) 
            task.title =  new_task_title
            task.is_important = new_task_imp
            task.save()
            return redirect('coreapp:main-page')
        else:
            tasks_list = Task.objects.filter(is_complete=False)
            context = {
            "form": edited_taskform,
            "tasks_list": tasks_list,
            "id": id,
            "error_mssg": ""
            }
            return render(request,"coreapp/edittask.html", context)

    
def ImportantTasksView(request):
    """ to list all incomplete important tasks """
    if request.method == 'GET':
        form = TaskForm()
        tasks_list = Task.objects.filter(is_important=True) & Task.objects.filter(is_complete=False) 
        context = {
            "form": form,
            "tasks_list": tasks_list
        }
        return render(request, 'coreapp/importanttasks.html', context)
    
    
def CompletedTasksView(request):
    """ to list all completed tasks"""
    tasks_list = Task.objects.filter(is_complete=True)
    context = {
            "form": TaskForm(),
            "tasks_list": tasks_list
    }
    return render(request, 'coreapp/completedtasks.html', context)
    
        
def DoneTaskView(request, id):
    """ to mark a task as completed"""
    task = get_object_or_404(Task,id=id)     
    task.is_complete = True
    task.save()
    return redirect('coreapp:main-page')


def DeleteTaskView(request, id):
    """ to delete a task"""
    task = get_object_or_404(Task,id=id) 
    task.delete()
    return redirect('coreapp:completed-tasks')


def IncompleteTaskView(request, id):
    """ to mark a task as incomplete"""
    task = get_object_or_404(Task,id=id) 
    task.is_complete = False
    task.save()
    return redirect('coreapp:main-page')



def custom_404(request, exception):
    return render(request, '404.html')

todoapp/coreapp/templates/base.html
{% load static %}

<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <meta name="viewport" content="width=device-width, initial-scale=1">
	    <title> ToDo </title>
        <!-- CSS -->        
        <link rel="stylesheet" href="https://bootswatch.com/5/flatly/bootstrap.min.css">
        <link rel="stylesheet" href="{% static 'css/style.css' %}" >
    </head>
    <body>
        {% block content %}    
        {% endblock %}
    </body>
</html>

todoapp/coreapp/templates/coreapp/completedtasks.html
{% extends "base.html" %}
{% load static %}


{% block content %}

<main class="container pt-5">
    <div class="container-md  text-center">
        <h1 class="h3"> Tasks Todo </h1>
    </div>
    <hr> 
    <div class="col text-center">
        <form action="/" method="POST">
            {% csrf_token %}
            <div class="col text-center">
                {% for field in form %}
                    {{ field.label|capfirst }}: &nbsp;  {{ field }} <br>
                    {% if field.errors %}
                        {{ field.errors }}
                    {% endif %}               
                {% endfor %}
            </div>
            &nbsp; 
            <div class="col text-center">
                <button type="submit"  class="btn btn-primary btn-md update-button">
                    Add </button>
                &nbsp; &nbsp; &nbsp; 
                <a type="button" class="btn btn-primary btn-sm update-button" 
                    href="{% url 'coreapp:main-page' %}"> Cancel </a>
                </div>
        </form>
    </div>
    <hr>
    <div class="col">
        &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;
        <a type="button" class="btn btn-primary btn-lg" 
            href="{% url 'coreapp:main-page' %}"> All Tasks </a> &nbsp; &nbsp; &nbsp; &nbsp;
        <a type="button" class="btn btn-primary btn-lg " 
            href="{% url 'coreapp:imp-tasks' %}"> Important Tasks </a>  &nbsp; &nbsp; &nbsp;
        <a type="button" class="btn btn-outline-primary btn-lg " 
            href="{% url 'coreapp:completed-tasks' %}"> Completed Tasks </a> 
        
    </div>
    <br>
    <div class="container bg-white shadow-lg p-5 mb-5 form-layout">
        <h1 class="h3"> Completed tasks </h1>
        <br>
        <ul>
        {% for task in tasks_list %}
            {% if  task.is_important == 1 %}
                <span>&#9733;</span> &nbsp;  {{ task.title | capfirst }} 
            {% else %}
                <span>&#9734;</span> &nbsp;  {{ task.title | capfirst }} 
            {% endif %}     
            <br>                       
            <div class="col">
                <a type="button" class="btn btn-outline-primary btn-sm update-button" 
                    href="{% url 'coreapp:incomplete-task' task.id %}"> NotDone </a>
                &nbsp; &nbsp; &nbsp;
                <a type="button" class="btn btn-outline-primary btn-sm update-button" 
                    href="{% url 'coreapp:delete-task' task.id %}"> Delete </a> 
            </div>
            <hr>
        {% endfor %}
        </ul>
    </div>
 
</main>

{% endblock %}

todoapp/coreapp/templates/coreapp/edittask.html
{% extends "base.html" %}
{% load static %}


{% block content %}

<main class="container pt-5">
    <div class="container-md  text-center">
        <h1 class="h3"> Edit Task </h1>
    </div>
    <hr> 
    <div class="col text-center">
        {% if error_mssg %} {{ error_mssg }} {% endif %}
    </div>
    &nbsp; 
    <div class="col text-center">
        <form action="{% url 'coreapp:edit-task' id%}" method="POST">
            {% csrf_token %}
            <div class="col text-center">
                {% for field in form %}
                    {{ field.label|capfirst }}: &nbsp;  {{ field }} <br>
                    {% if field.errors %}
                        {{ field.errors }}
                    {% endif %}               
                {% endfor %}
            </div>
            &nbsp; 
            
            <div class="col text-center">
                <button type="submit"  class="btn btn-primary btn-md update-button">
                    Add </button>
                &nbsp; &nbsp; &nbsp; 
                <a type="button" class="btn btn-primary btn-sm update-button" 
                    href="{% url 'coreapp:main-page' %}"> Cancel </a>
                </div>
        </form>
    </div>
    <hr>
    <div class="col">
        &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;
        <a type="button" class="btn btn-outline-primary btn-lg" 
            href="{% url 'coreapp:main-page' %}"> All Tasks </a> &nbsp; &nbsp; &nbsp; &nbsp;
        <a type="button" class="btn btn-primary btn-lg " 
            href="{% url 'coreapp:imp-tasks' %}"> Important Tasks </a> &nbsp; &nbsp; &nbsp;
        <a type="button" class="btn btn-primary btn-lg " 
            href="{% url 'coreapp:completed-tasks' %}"> Completed Tasks </a>
    </div>
    <br>
    <div class="container bg-white shadow-lg p-5 mb-5 form-layout">
        <h1 class="h3"> All tasks </h1>
        <br>
        <ul>
        {% for task in tasks_list %}
            {% if  task.is_important == 1 %}
                <span>&#9733;</span> &nbsp;  {{ task.title | capfirst }} 
            {% else %}
                <span>&#9734;</span> &nbsp;  {{ task.title | capfirst }} 
            {% endif %}     
            <br>                       
            <div class="col">
                <a type="button" class="btn btn-outline-primary btn-sm update-button" 
                    href="{% url 'coreapp:edit-task' task.id %}">Edit </a>
                &nbsp; &nbsp; &nbsp;
                <a type="button" class="btn btn-outline-primary btn-sm update-button" 
                    href="{% url 'coreapp:done-task' task.id %}">Done </a> 
            </div>
            <hr>
        {% endfor %}
        </ul>
    </div>
 
</main>

{% endblock %}

todoapp/coreapp/templates/coreapp/importanttasks.html
{% extends "base.html" %}
{% load static %}


{% block content %}

<main class="container pt-5">
    <div class="container-md  text-center">
        <h1 class="h3"> Tasks Todo </h1>
    </div>
    <hr> 
    <div class="col text-center">
        <form action="/" method="POST">
            {% csrf_token %}
            <div class="col text-center">
                {% for field in form %}
                    {{ field.label|capfirst }}: &nbsp;  {{ field }} <br>
                    {% if field.errors %}
                        {{ field.errors }}
                    {% endif %}               
                {% endfor %}
            </div>
            &nbsp; 
            <div class="col text-center">
                <button type="submit"  class="btn btn-primary btn-md update-button">
                    Add </button>
                &nbsp; &nbsp; &nbsp; 
                <a type="button" class="btn btn-primary btn-sm update-button" 
                    href="{% url 'coreapp:main-page' %}"> Cancel </a>
                </div>
        </form>
    </div>
    <hr>
    <div class="col">
        &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;
        <a type="button" class="btn btn-primary btn-lg" 
            href="{% url 'coreapp:main-page' %}"> All Tasks </a> &nbsp; &nbsp; &nbsp; &nbsp;
        <a type="button" class="btn btn-outline-primary btn-lg " 
            href="{% url 'coreapp:imp-tasks' %}"> Important Tasks </a>   &nbsp; &nbsp; &nbsp;
        <a type="button" class="btn btn-primary btn-lg " 
            href="{% url 'coreapp:completed-tasks' %}"> Completed Tasks </a> 
        
    </div>
    <br>
    <div class="container bg-white shadow-lg p-5 mb-5 form-layout">
        <h1 class="h3"> Important tasks </h1>
        <br>
        <ul>
        {% for task in tasks_list %}
            {% if  task.is_important == 1 %}
                <span>&#9733;</span> &nbsp;  {{ task.title | capfirst }} 
            {% else %}
                <span>&#9734;</span> &nbsp;  {{ task.title | capfirst }} 
            {% endif %}     
            <br>                       
            <div class="col">
                <a type="button" class="btn btn-outline-primary btn-sm update-button" 
                    href="{% url 'coreapp:edit-task' task.id %}">Edit </a>
                &nbsp; &nbsp; &nbsp;
                <a type="button" class="btn btn-outline-primary btn-sm update-button" 
                    href="{% url 'coreapp:done-task' task.id %}">Done </a> 
            </div>
            <hr>
        {% endfor %}
        </ul>
    </div>
 
</main>

{% endblock %}

todoapp/coreapp/templates/coreapp/mainpage.html
{% extends "base.html" %}
{% load static %}


{% block content %}

<main class="container pt-5">
    <div class="container-md  text-center">
        <h1 class="h3"> Tasks Todo </h1>
    </div>
    <hr> 
    <div class="col text-center">
        {% if error_mssg %} {{ error_mssg }} {% endif %}
    </div>
    &nbsp;
    <div class="col text-center">
        <form action="" method="POST">
            {% csrf_token %}
            <div class="col text-center">
                {% for field in form %}
                    {{ field.label|capfirst }}: &nbsp;  {{ field }} <br>
                    {% if field.errors %}
                        {{ field.errors }}
                    {% endif %}               
                {% endfor %}
            </div>
            &nbsp; 
            <div class="col text-center">
                <button type="submit" class="btn btn-primary btn-md update-button">
                    Add </button>
                &nbsp; &nbsp; &nbsp; 
                <a type="button" class="btn btn-primary btn-sm update-button" 
                    href="{% url 'coreapp:main-page' %}"> Cancel </a>
            </div>
        </form>
    </div>
    <hr>
    <div class="col">
        &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;
        <a type="button" class="btn btn-outline-primary btn-lg" 
            href="{% url 'coreapp:main-page' %}"> All Tasks </a> &nbsp; &nbsp; &nbsp; &nbsp;
        <a type="button" class="btn btn-primary btn-lg " 
            href="{% url 'coreapp:imp-tasks' %}"> Important Tasks </a> &nbsp; &nbsp; &nbsp;
        <a type="button" class="btn btn-primary btn-lg " 
            href="{% url 'coreapp:completed-tasks' %}"> Completed Tasks </a>
    </div>
    <br>
    <div class="container bg-white shadow-lg p-5 mb-5 form-layout">
        <h1 class="h3"> All tasks </h1>
        <br>
        <ul>
        {% for task in tasks_list %}
            {% if  task.is_important == 1 %}
                <span>&#9733;</span> &nbsp;  {{ task.title | capfirst }} 
            {% else %}
                <span>&#9734;</span> &nbsp;  {{ task.title | capfirst }} 
            {% endif %}     
            <br>                       
            <div class="col">
                <a type="button" class="btn btn-outline-primary btn-sm update-button" 
                    href="{% url 'coreapp:edit-task' task.id %}">Edit </a>
                &nbsp; &nbsp; &nbsp;
                <a type="button" class="btn btn-outline-primary btn-sm update-button" 
                    href="{% url 'coreapp:done-task'  task.id %}">Done </a> 
                
            </div>
            <hr>
        {% endfor %}
        </ul>
    </div>
 
</main>

{% endblock %}